### ISSUE TITLE
Do you pay for open source support via a third party organization?

### ISSUE THREAD

**Issue by caniszczyk** [todogroup/survey#14]

**Comment by LawrenceHecht** [comment]
What type of organization? Are we including when it is bundled in with a software offering that may have something proprietary in it?

**Comment by LawrenceHecht** [comment]
Option: 
Does your organization require commercial support for open source software used in production environments?
-Yes
-No
-Don't know

**Comment by LawrenceHecht** [comment]
For expediency's sake, I am closing this without adding a question.
