### ISSUE TITLE
What is your company's biggest risk when it comes to open source?

### ISSUE THREAD

**Issue by DuaneOBrien** [todogroup/survey#18]

**Comment by LawrenceHecht** [comment]
I think this is outside the scope of the survey.

**Comment by DuaneOBrien** [comment]
Why?

**Comment by LawrenceHecht** [comment]
@DuaneOBrien, 3/4 of a year later, here's your answer: The vast majority of the survey participants have already made the choice to use open source to some extent. Risk is an important topic to discuss, and I hope to cover it in terms of the risk that an OSPO is successful or not.
