### ISSUE TITLE
Do you participate in or use open source compliance initiatives (e.g. ClearlyDefined, OpenChain, Sharing-creates-value, Eclipse Oscano etc.)?

### ISSUE THREAD

**Issue by Toniprni** [todogroup/survey#19]

**Comment by LawrenceHecht** [comment]
This topic has value. I am concerned about us including Oscano b/c it appears to be a software solution, which can compete with vendor offerings. 

Also, "using" should be defined as more than reading an education piece.

**Comment by Toniprni** [comment]
I agree that Oscano is out of place in this question.

**Comment by caniszczyk** [comment]
taken care of https://github.com/todogroup/survey/pull/32
