### ISSUE TITLE
Which development tools and technologies do you use?

### ISSUE THREAD

**Issue by Toniprni** [todogroup/survey#20]
### Request and/or incident management tools:  
* Polarion  
* Team Foundation Server   
* JIRA   
* Github/Gitlab/other Git service  
* Other(s):   

### IDEs (Integrated Development Environments):
* Eclipse  
* Visual Studio  
* Qt Creator  
* Netbeans IDE  
* JetBrains CLion  
* JetBrains GoLand  
* JetBrains IntelliJ IDEA  
* JetBrains PhpStorm  
* JetBrains PyCharm  
* JetBrains Rider   
* JetBrains RubyMine  
* JetBrains WebStorm  
* Android Studio  
* Other(s):   

### Source code management (SCM) tools:
* SVN  
* Git  
* Other(s):  

### Source code management (SCM) services:
* GitLab  
* GitHub  
* Bitbucket  
* Sourceforge  
* Other(s):  

### Continuous integration (CI) and continuous deployment (CD) tools:  
* Jenkins  
* Team Foundation Server  
* Bamboo  
* TeamCity  
* CircleCI  
* Azure DevOps  
* Travis CI  
* GitLab CI  
* Concourse  
* AWS CodeBuild  
* Codeship  
* Drone.io  
* wercker  
* Go.CD  
* Semaphore  
* Appveyor  
* Buildkite  
* Puppet  
* Ansible  
* Octopus  
* Other(s):  

### Build tools, frameworks and dependency management:  
* Cmake  
* Yocto / OpenEmbedded  
* BitBake  
* Visual Studio  
* Apache Maven  
* Gradle  
* npm  
* yarn  
* pip / pipenv  
* Conda  
* Composer  
* sbt  
* Make  
* Apache Ant  
* Webpack  
* Other(s):  

### Package indexes and repositories  
* Go Search  
* npm registry  
* Packagist (the PHP package repository)  
* Maven repositories  
* RubyGems.org  
* NuGet  
* Bower  
* CPAN  
* Cargo (crates.io)  
* PEAR (PHP extension and application repository)  
* PlatformIO registry  
* Nexus Repository  
* JFrog Artifactory  
* CocoaPods  
* Other(s):  

### Document management:  
* Flowdock  
* Confluence  
* Polarion  
* Other(s):  

### Testing frameworks:  
* Robot Framework  
* Cypress  
* RedwoodHQ  
* Selenium  
* Serenity  
* Citrus Framework  
* TestRail  
* qTest  
* JUnit  
* AndroidTest  
* Roboelectric  
* mochito  
* Other(s):  

### Container technologies:  
* Docker  
* Cloud Foundry  
* Atomic  
* OpenShift  
* Kubernetes  
* Other(s):

**Comment by LawrenceHecht** [comment]
I think this is outside the scope of the survey.

**Comment by Toniprni** [comment]
I added this because answers to it would help understand the requirements for open source compliance toolings. Tools and processes need to be integrated and therefore it is useful to understand the popularity of certain technologies to help focus efforts with limited resources to more popular solutions.

**Comment by caniszczyk** [comment]
partially taken care of https://github.com/todogroup/survey/pull/32 but our goal is to not ask for every single tool used
