### ISSUE TITLE
Please consider adding following questions to the questionnaire

### ISSUE THREAD

**Issue by sriramhere** [todogroup/survey#3]
1) Are you in the business of developing or selling software applications?
 * Yes
 * No
2) If you use open source software, how do you use consume open source software?
 * Do-it-Yourself (DIY)
 * DIY with support from an open source software vendor
 * Through an open source software vendor, with support
 * Through an open source software vendor, without support
 * Through a managed service provider/ or a consultant
3) If you are using open source and you are not selling software applications, why do you use open source software?
 * To save on licensing costs
 * To provide flexibility and choice on software vendors 
 * Because my managed service provider recommended so
 * As a negotiation tactic while dealing with software vendors
 * Other
4) If you are NOT using open source, why are you NOT using open source software?
 * Lack of stability in the software
 * Lack of required features
 * Lack of support
 * Lack of expertise
 * Unpredictability in TCO estimates 
 * Other

**Comment by caniszczyk** [comment]
Thanks @sriramhere, I added your questions for 2019, we aren't ready to launch obviously for 2019 but we will include your questions there: https://github.com/todogroup/survey/commit/499eb52a8373dd04e620c1a823b92c2cce122623
