### ISSUE TITLE
Add a note to the survey that only one answer per company will be considered

### ISSUE THREAD

**Issue by CsatariGergely** [todogroup/survey#41]

**Comment by LawrenceHecht** [comment]
Good idea, but it is impossible to guarantee this will happen unless we get rid of some privacy guarantees.

**Comment by CsatariGergely** [comment]
As far as I understood the survey already considers only one answer per company. What I suggest here is to add a note about this to the beginning of the survey.

**Comment by LawrenceHecht** [comment]
The survey did not have a coded ban on having one respondent per company. I will make a note to add something at the front -- that way, people of good faith won't forward the survey around.

**Comment by caniszczyk** [comment]
@LawrenceHecht can you make a suggestion for this in the intro

**Comment by LawrenceHecht** [comment]
Added the intro text to the Questionnaire. 

Added this to the text: " Only one response per company will be included in the study's results. "

Closes this and committing the change.
