### ISSUE TITLE
How were participants were selected?

### ISSUE THREAD

**Issue by cben** [todogroup/survey#44]
Hi, coming here from reading https://thenewstack.io/research-shows-open-source-program-offices-improve-software-practices/.
Obviously the survey sampled only a tiny fraction of all companies in the world.
Please say something about how the survey was distributed / what kinds of companies was it targetted at?

Even if a reader trusts your conclusions  "the findings are not the result of self-selection bias", i.e. that it's a representative sample, it's unclear *a sample of what*.
For example there are probably no mom-and-pop-pizza shops here, or other completely offline businesses here...  Which I agree is out-of-scope to ask about OSPO and such :wink:, just making the point there *some* implicit scope and knowing it would be useful to the reader.

A bar chart of verticals [and company sizes] could go a long way towards answering this.
chart3 has number of answers by vertical:

| vertical | n |
| --- | --- |
| Defense | n=29 | 
| Education | n=112 |
| Financial services | n=127 |
| Government | n=66 |
| Healthcare | n=48 | 
| Insurance | n=24 |
| Manufacturing and raw materials | n=38 |
| Retail | n=57 |
| Technology (software or IT) | n=712 |
| Telecom, communications or media | n=142 |
| Transportation and automotive | n=58 |
| Utilities | n=30 |
| Other | n=180 |

But is that number of individual respondents, or number of companies?

---

BTW, are all the graphs weighted by number of respondents from same company / company size / normalized to 1 per company?
"One hundred and thirty responses were excluded because they appeared to come from the same company" — so I guess 1 per company, all weighted equally?

**Comment by LawrenceHecht** [comment]
@cben Here are some answers:

- The survey was conducted on July 8 – 29, 2019. Respondents were solicited via social media and with emails to The Linux Foundation, TODO Group, and The New Stack email lists. No type of company was targeted. 
- The study is representative of companies that use open source software.  Here is a table looking at the distribution by # of employees: 

| Q. How many people work for your company or organization? 2019, n=2671; 2018, n=748. | 2019  |
|--------------------------------------------------------------------------------------|-------|
| Self-employed or not working                                                         | 12.3% |
| 2-50                                                                                 | 22.8% |
| 51-250                                                                               | 15.7% |
| 251-1,000                                                                            | 13.0% |
| 1,001-10,000                                                                         | 14.4% |
| More than 10,000                                                                     | 20.8% |
| Don't know                                                                           | 1.1%  |

- The data represents individual respondents. We couldn't enforce a one-response per company rule without eliminating privacy protections for respondents. None of the charts are weighted.

**Comment by caniszczyk** [comment]
Thanks @LawrenceHecht
