### ISSUE TITLE
Ask question on how much open source you use

### ISSUE THREAD

**Issue by caniszczyk** [todogroup/survey#5]
- number of components
- % in products

**Comment by LawrenceHecht** [comment]
I like the % of components in products angle.

Asking about the number of components can be drastically different for big and small companies.

**Comment by LawrenceHecht** [comment]
I see that you added this at Q5. I am re-opening so we can discuss more.

We are already asking people how frequently they are using open source code in commercial products" in Q3.

This question, just gets more information about the percentage of their product mix that uses open source. We can take that part of Q3 out of the survey and replace with this question. **If we do that, then the answer choices should be:**

  Our products do not have any software components
  1-20%
  21-40%
  41-60%
  61-80%
  81-100%

**Alternatively, the question could be about the percentage of the components that are open source.**

**Comment by LawrenceHecht** [comment]
tweaked the wording, so closing again
