### ISSUE TITLE
Updating the open source compliance methodology question

### ISSUE THREAD

**Issue by LawrenceHecht** [todogroup/survey#53]
Q39. Which of the following open source compliance methodologies and initiatives does your organization utilize or participate in?

    ClearlyDefined
    FOSSology
    OpenChain
    Software Package Data Exchange (SPDX)
    Other (please specify)

If included in 2020, make this question required. Change question so that it asks whether or not they have any methodology or initiatives besides "homegrown", manual, etc.

**Comment by caniszczyk** [comment]
@LawrenceHecht have an idea on the specific change?

**Comment by LawrenceHecht** [comment]
Here is the revised question, which would be required:

Which open source compliance methodologies and initiatives does your organization utilize or participate in? (Check all that apply)
ClearlyDefined
FOSSology
OpenChain
Software Package Data Exchange (SPDX)
We utilize a homegrown or ad hoc methodology for open source compliance
We do not utilize or participate in any methodology or initiative
Other (please specify)
