### ISSUE TITLE
Get rid of benefits of using open source question

### ISSUE THREAD

**Issue by LawrenceHecht** [todogroup/survey#55]
Q42. Of the following options, what are the top three benefits your company receives by using open source software?

Presenting the results of this question are confusing. If kept it, can we make sure the choices mirror what is being asked in 1-2 other big studies?

**Comment by caniszczyk** [comment]
I'd not remove this and instead up for a modification

**Comment by LawrenceHecht** [comment]
OK, I will review and make a suggestion in the next 24-48 hours.

**Comment by LawrenceHecht** [comment]
I changed my mind about the need for updating the question. It is probably best to keep them as is for time series comparison.
