### ISSUE TITLE
2020 Survey dataset is missing data after question 47

### ISSUE THREAD

**Issue by caniszczyk** [todogroup/survey#76]
Hey @LawrenceHecht, can you investigate as we have some data missing apparently.

**Comment by LawrenceHecht** [comment]
Whoever found this issue was correct. It was missing the last column, the one for Industry Vertical. It is now fixed. All the other data not in the file was purposefully excluded because it has personally identifiable information.

**Comment by caniszczyk** [comment]
Thanks, fixed in https://github.com/todogroup/survey/commit/6223454315ffbb14b639bab24d1b9e2f662ce284
