### ISSUE TITLE
Pie chart % wrong (should be 23% instead of 24%)

### ISSUE THREAD

**Issue by jortkoopmans** [todogroup/survey#79]
Hello, just reviewed this pie chart (chart 11), shown below.
The pie chart for the sponsors of open source foundations is wrong, for the 'rarely or never' contributing percentage. I intuitively discovered this because the percentages cannot add up with max rounding (23.5%+27.5%+49.5% is over a 100).

Rarely or never contributing: 43/191 = **22.51 -> 23%**

I have crosschecked the counts to be correct in the csv (never/rarely=43, sometimes=53, frequent=95)

![alt text](https://github.com/todogroup/survey/raw/master/2020/chart11.svg?raw=true)

**Comment by jortkoopmans** [comment]
To clarify, this is for the 2020 survey.

**Comment by LawrenceHecht** [comment]
You are correct. I take responsibility for this mistake. The note was supposed to be there but the total was supposed to add up to 101% not 102% because of rounding. I will have this fixed and make a notation in the article it was published so people know there was an amendment.
