### ISSUE TITLE
Invalid data in results_2020.csv

### ISSUE THREAD

**Issue by vmbrasseur** [todogroup/survey#80]
Importing the CSV file to a spreadsheet, you see that some columns (K, AM for instance) contain data interpreted as dates that should be numbers. Looking at the CSV source, you see the same thing there. It looks like someone imported data into their spreadsheet software then exported it as a CSV without verifying their software hadn't "helpfully" reformatted the data for them. For example, note the "Feb-50" in the CSV entry below:

> 11696528278,6/14/2020 16:31,6/14/2020 16:41,Consuming open source code in products or services,,,,Collaborating with peers across open source projects and/or foundations,,,Feb-50,Rarely,Frequently,Never,Never,Never,Never,Sometimes,1-20%,No,No,No,No,No,No,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,Organizations open source use and participation is too small to need one,,,,,,,No,,,,,,,,,,,,,,,,,,,,,,,Organization's open source use and participation is too small to need one,,,,,,,,Very Poor,Don't know,Don't know,Above Average,Above Average,Below Average,Excellent,Very Poor,Don't know,Don't know,Don't know,Very influential,No,Neutral,No,,0,Dont know,5-Jan,No,No preference,,,,,,,,,,,,,,,,,,,,,,,We do not utilize a tool or methodology for open source compliance,,,No,,,,,Homegrown solution,,,,,Functionality,Performance and stability,,,,,Total cost of ownership (licenses and developer time),,,Other IT,

Could we please get a CSV file with unmunged data for all of the columns?

/attn @LawrenceHecht

**Comment by LawrenceHecht** [comment]
Fixed. Note that the actual data starts in the 3rd row.

**Comment by zesoup** [comment]
Hey there!
The Issue seems to persist on the Master-Branch as numerous size indicators are still interpreted as dates in the results_2020.csv.

**Comment by LawrenceHecht** [comment]
It should be fixed now, again -- I went back and converted all fields to text format before converting to csv. Apologies.
