### ISSUE TITLE
Confirm company's main open source investment (area from which they derive most business value) 

### ISSUE THREAD

**Issue by sstruble** [todogroup/survey#82]
Part 1, after question 4: Suggest adding: What do you consider to be your company's dominant open source investment?

**Comment by LawrenceHecht** [comment]
We did not address the "business value" aspect of this question.  We did ask, 

"Which technology area does your company focus its open source activities on? (Check all that apply)
AI, ML, Data & Analytics
Blockchain
CI/CD & Site Reliability
Cloud
Containers & Virtualization
DevOps
IoT & Embedded
Networking & Edge
Open Hardware
Safety-Critical Systems
Security
Storage
System Administration
Web & Application Development
