### ISSUE TITLE
Add question about relevance to core business

### ISSUE THREAD

**Issue by sstruble** [todogroup/survey#84]
Part 1, after Q4 suggest adding how relevant is your main open source investment to your organization’s core business? 

- Untapped: could substitute proprietary software without recognizable change
- Beneficial: beneficial to core business, but could deliver same value without open source but at a higher cost 
- Dependent: core product couldn’t exist without it 
- Promotional: open source is essential to promotion of core product (e.g. accompanying SDK or components) 
- Accelerant: working with external open source community shortens time-to-value creation/capture 
- Direct: main business value is derived directly off open source, e.g. GitLab 

(I’m unsure how to resolve this with Part 8 question, which are more focused on operational value. This question is aimed a bit differently)

**Comment by LawrenceHecht** [comment]
@sstruble I know where this question is coming from. The issue is that the Part 8 question needs to be taken out of the survey. 

There is an almost identical question to this in another survey done by OpenForum Europe. I am writing the author now for the 3rd time...

**Comment by LawrenceHecht** [comment]
Did not add this question. Instead, trying to add a question about how strategic open source is to the business.  The key issue is that this question delves too much into business models.
