### ISSUE TITLE
Add question about formal monitoring of cross-org dependencies 

### ISSUE THREAD

**Issue by sstruble** [todogroup/survey#85]
Somewhere in Part 2: Does your company monitor cross-organizational open source dependencies? 

- Yes - informally 
- Yes- formally 
- I don’t know
- No

This could also be turned into another line item in Part 1/Question 3, although I think it would be interesting to ask this separately as a more operationally focused question

**Comment by LawrenceHecht** [comment]
How are they monitoring it? Do they think it is important?

**Comment by LawrenceHecht** [comment]
Decided not to include because this goes deep into SCA and SBOM capabilities and governance requirements.
