### ISSUE TITLE
Add line items to capture relevance of open source investments to strengthening/building partnerships? 

### ISSUE THREAD

**Issue by sstruble** [todogroup/survey#87]
There are a few instances where I'd include this, such as Part 2/Q15, Part 3/Q24, Q25, Part 4B/Q30 (hopefully I didn't miss any there). fwiw from personal experience, this was always key in my projects, and it also relates to better understanding how companies are handling cross-org dependencies

**Comment by LawrenceHecht** [comment]
Can a separate question be asked about using open source as a way to further strategic relationships and partnerships? That would simplify things.

**Comment by DuaneOBrien** [comment]
What would that look like?

**Comment by LawrenceHecht** [comment]
In the draft, there is a question "Does your company use its open source program office as a way to further its strategic relationships and build partnerships?"

That is not a perfect question, just a first step.

**Comment by LawrenceHecht** [comment]
see this [commit](https://github.com/todogroup/survey/commit/1da7888a13fc72911393d84514e22b8fa94b4d79)
