### ISSUE TITLE
Does your company allow open source contributions in their spare time?

### ISSUE THREAD

**Issue by caniszczyk** [todogroup/survey#9]
maybe a question around the employment agreements structure for open source contribution

**Comment by LawrenceHecht** [comment]
Here is the specific question in the GitHub 2017 survey:
![github2017-a](https://user-images.githubusercontent.com/9385056/58829975-2aaf1d80-8617-11e9-8b7d-d8b47fa0a84a.png)

Would you like a question that asks about a list of 5-7 specific OSS-specific policies that companies may have?
